execution:
    uuid: e964d7b5-93f0-426a-bb0d-aff76372ddec
    runtime:
        start: 2021-01-08T15:26:44.913369-08:00
        end: 2021-01-08T15:40:48.611584-08:00
        duration: 14 minutes, 3 seconds, and 698215 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:micom'
    action: db
    inputs: []
    parameters:
    -   meta: !metadata 'meta.tsv'
    -   rank: genus
    -   threads: 10
    output-name: metabolic_models
    citations:
    - !cite 'action|micom:0.10.1|method:db|0'
    - !cite 'action|micom:0.10.1|method:db|1'
    - !cite 'action|micom:0.10.1|method:db|2'

transformers:
    output:
    -   from: JSONDirectory
        to: JSONDirectory

environment:
    platform: linux-x86_64
    python: |-
        3.6.12 | packaged by conda-forge | (default, Dec  9 2020, 00:36:02)
        [GCC 9.3.0]
    framework:
        version: 2020.11.1
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2020.11.1|0'
    plugins:
        micom:
            version: 0.10.1
            website: https://github.com/micom-dev/q2-micom
    python-packages:
        zipp: 3.4.0
        xopen: 1.0.1
        widgetsnbextension: 3.5.1
        wheel: 0.36.1
        webencodings: 0.5.1
        wcwidth: 0.2.5
        urllib3: 1.25.11
        unifrac: 0.20.1
        tzlocal: '2.1'
        typing-extensions: 3.7.4.3
        traitlets: 4.3.3
        tqdm: 4.54.1
        tornado: '6.1'
        toml: 0.10.2
        threadpoolctl: 2.1.0
        testpath: 0.4.4
        terminado: 0.9.1
        tabulate: 0.8.7
        sympy: 1.6.2
        symengine: 0.6.1
        swiglpk: 4.65.1
        statsmodels: 0.12.1
        sniffio: 1.1.0
        six: 1.15.0
        setuptools: 49.6.0.post20201009
        sepp: 4.3.10
        Send2Trash: 1.5.0
        seaborn: 0.11.0
        scipy: 1.5.3
        scikit-learn: 0.23.1
        scikit-bio: 0.5.6
        ruamel.yaml: 0.16.12
        ruamel.yaml.clib: 0.2.2
        rich: 6.2.0
        rfc3986: 1.4.0
        requests: 2.25.0
        qiime2: 2020.11.1
        q2templates: 2020.11.1
        q2cli: 2020.11.1
        q2-vsearch: 2020.11.1
        q2-types: 2020.11.1
        q2-taxa: 2020.11.1
        q2-sample-classifier: 2020.11.1
        q2-quality-filter: 2020.11.1
        q2-quality-control: 2020.11.1
        q2-phylogeny: 2020.11.1
        q2-micom: 0.10.1
        q2-metadata: 2020.11.1
        q2-longitudinal: 2020.11.1
        q2-gneiss: 2020.11.1
        q2-fragment-insertion: 2020.11.1
        q2-feature-table: 2020.11.1
        q2-feature-classifier: 2020.11.1
        q2-emperor: 2020.11.1
        q2-diversity: 2020.11.1
        q2-diversity-lib: 2020.11.1
        q2-demux: 2020.11.1
        q2-deblur: 2020.11.1
        q2-dada2: 2020.11.1
        q2-cutadapt: 2020.11.1
        q2-composition: 2020.11.1
        q2-alignment: 2020.11.1
        pyzmq: 20.0.0
        PyYAML: 5.3.1
        pytz: '2020.4'
        python-libsbml: 5.19.0
        python-libsbml-experimental: 5.18.3
        python-dateutil: 2.8.1
        pytest: 6.1.2
        PySocks: 1.7.1
        pyrsistent: 0.17.3
        pyparsing: 2.4.7
        pyOpenSSL: 20.0.0
        Pygments: 2.7.3
        pydantic: 1.7.3
        pycparser: '2.20'
        py: 1.9.0
        ptyprocess: 0.6.0
        psutil: 5.7.3
        prompt-toolkit: 3.0.8
        prometheus-client: 0.9.0
        pluggy: 0.13.1
        pipdeptree: 1.0.0
        pip: 20.3.1
        Pillow: 8.0.1
        pickleshare: 0.7.5
        pexpect: 4.8.0
        patsy: 0.5.1
        parso: 0.7.1
        pandocfilters: 1.4.2
        pandas: 1.1.5
        packaging: '20.7'
        optlang: 1.4.4
        olefile: '0.46'
        numpy: 1.19.4
        notebook: 6.1.5
        nose: 1.3.7
        networkx: '2.5'
        nest-asyncio: 1.4.3
        nbformat: 5.0.8
        nbconvert: 6.0.7
        nbclient: 0.5.1
        natsort: 7.1.0
        msgpack: 1.0.0
        mpmath: 1.1.0
        more-itertools: 8.6.0
        mistune: 0.8.4
        micom: 0.20.2
        matplotlib: 3.2.2
        MarkupSafe: 1.1.1
        lz4: 3.1.1
        loguru: 0.5.3
        lockfile: 0.12.2
        kiwisolver: 1.3.1
        jupyterlab: 2.2.9
        jupyterlab-server: 1.2.0
        jupyterlab-pygments: 0.1.2
        jupyter-core: 4.7.0
        jupyter-client: 6.1.7
        jsonschema: 3.2.0
        json5: 0.9.5
        joblib: 0.17.0
        Jinja2: 2.11.2
        jedi: 0.17.2
        ipywidgets: 7.5.1
        ipython: 7.16.1
        ipython-genutils: 0.2.0
        ipykernel: 5.3.4
        iniconfig: 1.1.1
        importlib-resources: 3.3.0
        importlib-metadata: 3.1.1
        immutables: '0.14'
        ijson: 3.1.3
        idna: '2.10'
        hyperframe: 5.2.0
        httpx: 0.16.1
        httpcore: 0.12.2
        hpack: 3.0.0
        hdmedians: 0.14.1
        h11: 0.9.0
        h5py: 2.10.0
        h2: 3.2.0
        gneiss: 0.4.6
        gmpy2: 2.0.8
        future: 0.18.2
        fastcluster: 1.1.26
        fastcache: 1.1.0
        entrypoints: '0.3'
        emperor: 1.0.1
        dnaio: 0.4.4
        diskcache: 5.1.0
        depinfo: 1.5.4
        DendroPy: 4.5.1
        defusedxml: 0.6.0
        decorator: 4.4.2
        deblur: 1.1.0
        dataclasses: '0.7'
        Cython: 0.29.21
        cycler: 0.10.0
        cutadapt: '3.1'
        cryptography: 3.3.1
        cplex: 12.10.0.0
        contextvars: '2.4'
        commonmark: 0.9.1
        colorama: 0.4.4
        cobra: 0.20.0
        click: 7.1.2
        chardet: 3.0.4
        cffi: 1.14.4
        certifi: 2020.12.5
        CacheControl: 0.12.6
        brotlipy: 0.7.0
        bokeh: 2.2.3
        bleach: 3.2.1
        biom-format: 2.1.10
        bibtexparser: 1.1.0
        backports.functools-lru-cache: 1.6.1
        backcall: 0.2.0
        attrs: 20.3.0
        async-generator: '1.10'
        argon2-cffi: 20.1.0
        appdirs: 1.4.4
        aiocontextvars: 0.2.2
